#include "conf.h"
#include "env.h"

// This file is generated by `make generate_config`. Do not edit it manually.

// Init a configuration file with environment variables.
void wrd_init_config(wrd_config *config) {
    // Database
    config->db_path = wrd_get_env_string("WRD_DB_PATH", WRD_DEFAULT_DB_PATH);
    // Net
    config->listen_backlog = wrd_get_env_int("WRD_LISTEN_BACKLOG", WRD_DEFAULT_LISTEN_BACKLOG);
    config->max_columns = wrd_get_env_int("WRD_MAX_COLUMNS", WRD_DEFAULT_MAX_COLUMNS);
    config->net_buffer_size = wrd_get_env_int("WRD_NET_BUFFER_SIZE", WRD_DEFAULT_NET_BUFFER_SIZE);
    config->net_headers_buffer_size = wrd_get_env_int("WRD_NET_HEADERS_BUFFER_SIZE", WRD_DEFAULT_NET_HEADERS_BUFFER_SIZE);
    config->net_input_buffer_size = wrd_get_env_int("WRD_NET_INPUT_BUFFER_SIZE", WRD_DEFAULT_NET_INPUT_BUFFER_SIZE);
    config->socket_port = wrd_get_env_int("WRD_SOCKET_PORT", WRD_DEFAULT_SOCKET_PORT);
}

// Load a configuration file.
void wrd_load_config(wrd_config *config, const char *input) {
    wrd_init_config(config);
}
